### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by iferres** [iferres/phylen#18]
# My TODO checklist
- [x] Add more parameters to control phylogenetic inference step. **branch develop**
- [ ] Add more methods.
- [ ] Change from super-gene phylogenetic inference to consensus from many alignments.
- [ ] Apply "phylogenetic" algorithm to select between paralogues.
- [ ] Add option or create new branch to take into account gene length when merging into orthologous groups. This will be useful to create cgMLST schemes.
